### ISSUE TITLE
Will there be a branch for Dynamo 1.0? 

### ISSUE THREAD

**Issue by NicklasOestergaard** [DynamoDS/DynamoSamples#11]
Will there be a branch for Dynamo 1.0?

**Comment by sharadkjaiswal** [comment]
Is there specific reason that you are looking for Dynamo 1.0 branch?

**Comment by NicklasOestergaard** [comment]
It appears that much has change in the api and therefore an example/sample would be great help.

**Comment by sharadkjaiswal** [comment]
This repo has been updated to build based on the new API set. Please let us know if you find any issue.

**Comment by NicklasOestergaard** [comment]
So the master branch is allrady updated to Dynamo 1.0 ? Thanks.

**Comment by NicklasOestergaard** [comment]
@sharadkjaiswal I get a lot off erros when I try to buld the solution from master. It looks like the packages have been updated to version 1.0 but the code is still in 9.0.?
