### ISSUE TITLE
Samples not working in Dynamo Sandbox correctly...

### ISSUE THREAD

**Issue by DanimoSite** [DynamoDS/DynamoSamples#22]
Hi,

I'm looking to get going with the examples in this repo, but I am running into errors. I'm specifically interested in View Extensions, but when I compile and copy into the Dynamo Root folder, the View Extension example doesn't seem to work and there are a few hangups on some other nodes.

Any help would be greatly appreciated...

I'm using Dynamo 1.3, windows 10 and testing in Dynamo Sandbox, building in VS 2017 community and copied the latest Master from here. 

![image](https://user-images.githubusercontent.com/37482336/37558503-17de569c-2a0d-11e8-9957-1a987504fe13.png)

Thanks in advance,
D

**Comment by mjkkirschner** [comment]
let's separate the node from view extension issue and first things first:

the master branch of this repo is for dynamo 2.x
for 1.3 use the 1.3 branch.

**Comment by DanimoSite** [comment]
Hi @mjkkirschner ,

Yup! Sorry, it pains me to admit it, but I was testing against the wrong version. 🙄 

Apologies...
