### ISSUE TITLE
DynamoSamples uses a different version of NUnit compared to Dynamo (Dynamo.All)

### ISSUE THREAD

**Issue by thomas-gale** [DynamoDS/DynamoSamples#24]
Windows 10 (x64)
Visual Studio 2017 (15.6.3)
NUnit VS Adapter 2.1.1.0
Revit 2018 installed (for ASM libraries)

At the time of writing, the [master branch of Dynamo](https://github.com/DynamoDS/Dynamo/commit/549d2572359e405924e027194a40bb8156dd835c) is using [nunit.framework.dll](https://github.com/DynamoDS/Dynamo/blob/master/extern/NUnit/nunit.framework.dll) version 2.6.2.12296.

However, [the master branch of DynamoSamples](https://github.com/DynamoDS/DynamoSamples/commit/98aaf72b58455d8e44157d432c5473578a522f43) (in the sample library tests) is referencing the [NUnit package](https://github.com/DynamoDS/DynamoSamples/blob/master/src/SampleLibraryTests/packages.config) version 2.6.3.

Due to this versioning difference, running DynamoSamples/SampleLibraryTests will result in a FileLoadException from Visual Studio's NUnit 2.1.1.0 test runner.

![image](https://user-images.githubusercontent.com/11990706/38633723-6e8ba828-3db8-11e8-8393-f05fe39257f6.png)

To resolve this issue, ensure that DynamoSamples copies out the nunit.framework.dll v2.6.3 into the Dynamo binary folder (overwriting Dynamo's v.2.6.2)

![image](https://user-images.githubusercontent.com/11990706/38633935-03f61812-3db9-11e8-9cc5-2eda92d96e33.png)

This whole issue of NUnit assembly resolution might have been specific to my (possibly incorrectly configured) build DynamoSamples and Dynamo environment. However, I thought I would share this problem, with the hope that it can save frustration for anyone else in the future.

**Comment by thomas-gale** [comment]
One additional comment to add. Due to using Revit 2018. I needed to also configure Dynamo's ProtoGeometry.config to use libg_223.

![image](https://user-images.githubusercontent.com/11990706/38732011-83d3c35c-3f14-11e8-94d1-5a1afd4a0fcf.png)

**Comment by Racel** [comment]
@alfarok @mjkkirschner @QilongTang Can you take a look at this? Should we be updating the nuget for the 2.0.1 hotfix after all?

**Comment by alfarok** [comment]
@Racel Dynamo includes a version of NUnit that isn't a NuGet reference.  I think the simple solution is to just to roll back the version used in the samples to coordinate with Core.

**Comment by Racel** [comment]
@alfarok Sounds good. Let's just roll back the version of NUnit in Samples, then. Can you file a task for next sprint? Or will it take just as long to just do it?

**Comment by alfarok** [comment]
@Racel Should be a quick fix but I'll file a task so it's tracked and can get some testing.

**Comment by alfarok** [comment]
Tracking with [QNTM-4186](https://jira.autodesk.com/browse/QNTM-4186)

**Comment by alfarok** [comment]
@ThomasGale @radumg FYI, this should be addressed with [Dynamo #8914](https://github.com/DynamoDS/Dynamo/pull/8914).  Thanks for the details regarding the original issue.
