### ISSUE TITLE
Sample update -> 1.x.x.x

### ISSUE THREAD

**Issue by erfajo** [DynamoDS/DynamoSamples#8]
When will the DynamoSamples be updated to the new dynamocore (1.x.x.x)?

**Comment by riteshchandawar** [comment]
Do you have specific Sample not working on Dynamo 1.0.0 which needs to be updated?

We are updating Import/Export samples in this PR...https://github.com/DynamoDS/Dynamo/pull/6238

**Comment by erfajo** [comment]
Well I had to change the whole core, and reload it from Nuget
I figured that namespace DSCoreNodesUI was changed to CoreNodeModels
But there could be a lot of other stuff which is outdated and should/could be fixed. So please make a new sample for version 1.x.x.x

---

Fra: riteshchandawar [mailto:notifications@github.com] 
Til: DynamoDS/DynamoSamples DynamoSamples@noreply.github.com
Emne: Re: [DynamoSamples] Sample update -> 1.x.x.x (#8)

Do you have specific Sample not working on Dynamo 1.0.0 which needs to be updated?
We are updating Import/Export samples in this PR...DynamoDS/Dynamo#6238 https://github.com/DynamoDS/Dynamo/pull/6238
